from flask import Flask, render_template, request, redirect, session, url_for

app = Flask(__name__)
app.secret_key = "voting_secret"

# 👇 ADD THIS BELOW
@app.route("/constituency/<name>")
def constituency_parties(name):

    data = {
        "Tiruttani": ["party_dmk.png", "party_admk.png", "party_tvk.png", "party_ntk.png", "party_pmk.png", "party_bjp.png", "party_congress.png"],
        "Thiruvallur": ["party_dmk.png", "party_admk.png", "party_tvk.png", "party_ntk.png", "party_pmk.png", "party_bjp.png", "party_congress.png"],
        "Ambattur": ["party_dmk.png", "party_admk.png", "party_tvk.png", "party_ntk.png", "party_pmk.png", "party_bjp.png", "party_congress.png"],
    }

    parties = data.get(name, [])

    return render_template("parties.html", name=name, parties=parties)
# ---------------- CONSTITUENCY LIST ----------------
constituencies = [
"Gummidipoondi","Ponneri (SC)","Tiruttani","Thiruvallur","Poonamallee (SC)",
"Avadi","Maduravoyal","Ambattur","Madhavaram","Tiruvottiyur",
"Dr. Radhakrishnan Nagar","Perambur","Kolathur","Villivakkam","Thiru-Vi-Ka-Nagar (SC)",
"Egmore (SC)","Royapuram","Harbour","Chepauk-Thiruvallikeni","Thousand Lights",
"Anna Nagar","Virugambakkam","Saidapet","T. Nagar","Mylapore",
"Velachery","Sholinganallur","Alandur","Sriperumbudur (SC)","Pallavaram",
"Tambaram","Chengalpattu","Thiruporur","Cheyyur (SC)","Madurantakam (SC)",
"Uthiramerur","Kancheepuram","Arakkonam (SC)","Sholingur","Katpadi",
"Ranipet","Arcot","Vellore","Anaikattu","Kilvaithinankuppam (SC)",
"Gudiyattam (SC)","Vaniyambadi","Ambur","Jolarpet","Tirupattur",
"Uthangarai (SC)","Bargur","Krishnagiri","Veppanahalli","Hosur",
"Thalli","Palacode","Pennagaram","Dharmapuri","Pappireddippatti",
"Harur (SC)","Chengam (SC)","Tiruvannamalai","Kilpennathur","Kalaiyarkovil",
"Arani","Polur","Cheyyar","Vandavasi (SC)","Gingee",
"Mailam","Tindivanam (SC)","Vanur (SC)","Villupuram","Vikravandi",
"Tirukoilur","Ulundurpettai","Rishivandiyam","Sankarapuram","Kallakurichi (SC)",
"Gangavalli (SC)","Attur (SC)","Yercaud (ST)","Omalur","Salem North",
"Salem South","Salem West","Edappadi","Mettur","Veerapandi",
"Sankari","Rasipuram (SC)","Senthamangalam (ST)","Namakkal","Paramathi-Velur",
"Tiruchengode","Kumarapalayam","Erode East","Erode West","Modakkurichi",
"Dharapuram (SC)","Kangayam","Perundurai","Bhavani","Anthiyur",
"Gobichettipalayam","Bhavanisagar (SC)","Udhagamandalam","Gudalur (SC)","Coonoor",
"Mettupalayam","Avanashi (SC)","Tiruppur North","Tiruppur South","Palladam",
"Udumalpet","Madathukulam","Pollachi","Kinathukadavu","Valparai (SC)",
"Singanallur","Coimbatore North","Coimbatore South","Kavundampalayam","Thondamuthur",
"Perur","Sulur","Karur","Krishnarayapuram (SC)","Kulithalai",
"Manapparai","Srirangam","Tiruchirappalli West","Tiruchirappalli East","Thiruverumbur",
"Lalgudi","Musiri","Thuraiyur (SC)","Perambalur (SC)","Kunnam",
"Ariyalur","Jayankondam","Tittagudi (SC)","Vriddhachalam","Neyveli",
"Panruti","Cuddalore","Kurinjipadi","Bhuvanagiri","Chidambaram",
"Kattumannarkoil (SC)","Sirkazhi (SC)","Mayiladuthurai","Poompuhar","Nagapattinam",
"Kilvelur (SC)","Vedaranyam","Thiruthuraipoondi (SC)","Mannargudi","Thiruvarur",
"Nannilam","Thanjavur","Orathanadu","Papanasam","Kumbakonam",
"Tiruvaiyaru","Thiruvonam","Pattukkottai","Peravurani","Gandharvakottai (SC)",
"Viralimalai","Pudukkottai","Thirumayam","Alangudi","Aranthangi",
"Karaikudi","Sivaganga","Manamadurai (SC)","Melur","Madurai East",
"Sholavandan (SC)","Madurai North","Madurai South","Madurai Central","Madurai West",
"Thiruparankundram","Thirumangalam","Usilampatti","Andipatti","Periyakulam (SC)",
"Bodinayakanur","Cumbum","Rajapalayam","Srivilliputhur (SC)","Sattur",
"Sivakasi","Virudhunagar","Aruppukkottai","Tiruchuli","Paramakudi (SC)",
"Tiruvadanai","Ramanathapuram","Mudukulathur","Vilathikulam","Thoothukkudi",
"Tiruchendur","Srivaikuntam","Ottapidaram (SC)","Kovilpatti","Sankarankovil (SC)",
"Vasudevanallur (SC)","Kadayanallur","Tenkasi","Alangulam","Tirunelveli",
"Palayamkottai","Ambasamudram","Nanguneri","Radhapuram","Kanyakumari",
"Nagercoil","Colachel","Padmanabhapuram","Vilavancode","Kulachal"
]


# ---------------- LANGUAGE DATA ----------------

languages = {

    "en": {
        "welcome": "Welcome to Online Voting",
        "tagline": "Secure • Transparent • Digital India",
        "vote": "Vote Now",
        "gov": "Government of India | Online Voting System",
        "home": "Home",
        "about": "About",
        "service": "Service",
        "manifesto": "Party Manifesto",
        "login": "Login",
        "title": "Online Voting System – Election Commission of India",
        "ministry": "Ministry of Digital Affairs, Government of India",
        "about_title": "About Online Voting",
        "result": "Result",
        "about_desc": "Online Voting System is a secure digital platform that enables citizens to cast votes remotely. It ensures transparency, eliminates duplicate voting, and provides instant election results.",
        "features_title": "Key Features",
        "secure_voting": "Secure Voting",
        "auth_system": "Advanced authentication system",
        "one_vote": "One Person One Vote",
        "no_duplicate": "Duplicate votes blocked",
        "instant_results": "Instant Results",
        "live_count": "Live vote counting",
        "multi_lang": "Multi Language",
        "accessible": "Accessible for all citizens",
        "stats": "Election Statistics",
        "voters": "Registered Voters",
        "votes": "Votes Casted",
        "parties": "Political Parties",
        "how": "How It Works",
        "step1": "Register with Voter ID",
        "step2": "Login securely",
        "step3": "Select your party",
        "step4": "Submit your vote",
        "step5": "View election results",
        "footer1": "Online Voting System",
        "footer2": "Election Commission of India",
        "about_title_full": "About Online Voting System",
        "eci": "Election Commission of India",
        "intro_title": "Introduction",
        "intro_desc":  "The Online Voting System is a digital platform developed to modernize the election process. It allows citizens to cast their votes securely from anywhere without visiting polling booths.",
        "mission_title": "Our Mission",
        "mission_desc": "Our mission is to make voting accessible, transparent, and secure using modern technology. We aim to increase voter participation and ensure fair elections",
        "security_title": "Security & Transparency",
        "security_desc": "The system uses voter ID verification and authentication to prevent duplicate voting. Each voter can vote only once.",
        "tech_title": "Technology Used",
        "tech_desc": "This system is built using Flask (Python), HTML, CSS, JavaScript, and database technologies to ensure speed, reliability, and security.",
        "benefits": "Benefits",
        "b1": "Vote from anywhere",
        "b2": "Instant result counting",
        "b3": "Eco-friendly paperless system",
        "b4": "Saves time and cost",
        "back": "Back to Home",
        "footer_main": "Online Voting System",
        "footer_gov": "Government of India",
        "success": "Vote Submitted Successfully!",
        "thanks": "Thank you for casting your vote.",
        "back": "Back to Home",
        "reg_title": "Voter Registration",
        "reg_desc": "Citizens can register online using Voter ID and Aadhaar details.",
        "login_title": "Secure Login",
        "login_desc": "Multi-level authentication system ensures safe voter access.",
        "vote_title": "Cast Vote",
        "vote_desc": "Voters can cast their vote digitally from anywhere.",
        "dup_title": "Duplicate Vote Prevention",
        "dup_desc": "System blocks multiple voting by the same voter.",
        "lang_title": "Multi-Language Support",
        "lang_desc": "Available in regional languages for accessibility.",
        "cand_title": "Candidate Information",
        "cand_desc": "Displays candidate and party details before voting.",
        "live_title": "Live Results",
        "live_desc": "Instant vote counting with transparent result display.",
        "admin_title": "Admin Monitoring",
        "admin_desc": "Election officers monitor voting and manage the system.",
        "footer": "Online Voting System | Government of India",
        "service_title": "Our Services",
        "eci": "Election Commission of India",
         "manifesto_title": "Party Manifesto (Katchi Kolkai)",
        "manifesto_sub": "Election Policies & Participant Details",
        "participants": "Election Participants: 120 Candidates",

        "p1": "Free Education Scheme",
        "p2": "Women Empowerment",
        "p3": "Job Creation Programs",
        "p4": "Healthcare Access for All",
        "p5": "Environmental Sustainability Initiatives",
        "p6": "Affordable Housing for All",
        "p7": "Digital Literacy & Internet Access in Rural Areas",
        "p8": "Support for Arts, Culture & Heritage",
        "p9": "Renewable Energy Promotion",
        "p10": "Child Nutrition & Midday Meal Improvement",
        "p11": "Public Transport Expansion & Modernization",
        "p12": "Anti-Corruption Transparency Measures",
        "p13": "Affordable Healthcare for Senior Citizens",
        "p14": "Skill Development & Vocational Training",
        "p15": "Women Safety & Legal Aid Programs",
        "p16": "Support for Startups & Small Businesses",
        "p17": "Urban Green Spaces & Parks Development",
        "p18": "Digital Governance & E-Services Expansion",
        "p19": "Farmer Support Funds",
        "p20": "Free Medical Camps",
        "p21": "Rural Development",
        "p22": "Women & Child Welfare Programs",
        "p23": "Urban Infrastructure Improvement",
        "p24": "Affordable Housing for Low-Income Families",
        "p25": "Clean Drinking Water Projects",
        "p26": "Renewable Energy Promotion",
        "p27": "Digital Literacy & e-Governance Access",
        "p28": "Public Health & Vaccination Drives",
        "p29": "Skill Development & Employment Programs",
        "p30": "Transport & Road Modernization",
        "p31": "Support for Small & Medium Enterprises",
        "p32": "Environmental Conservation Initiatives",
        "p33": "Senior Citizens Welfare Programs",
        "p34": "Child Nutrition & Midday Meal Improvements",
        "participants2": "Election Participants: 110 Candidates",
        "p35": "Digital India Expansion",
        "p36": "Startup Funding",
        "p37": "Infrastructure Growth",
        "p38": "Smart City Projects",
        "p39": "Skill Development & Vocational Training",
        "p40": "Make in India Initiatives",
        "p41": "Renewable Energy Promotion (solar & wind)",
        "p42": "Public Transportation Modernization",
        "p43": "Healthcare Access & Insurance Schemes",
        "p44": "Education Loan Assistance",
        "p45": "Rural Development & Irrigation Projects",
        "p46": "Support for Small & Medium Enterprises (SMEs)",
        "p47": "Women Empowerment Programs",
        "p48": "Urban Green Spaces & Parks Development",
        "p49": "Anti-Corruption & Governance Transparency",
        "p50": "Digital Governance & E-Services Expansion",
        "participants3": "Election Participants: 95 Candidates",
        "p51": "Youth Employment Plan",
        "p52": "Health Insurance",
        "p53": "Education Loan Waiver",
        "p54": "Affordable Housing Schemes",
        "p55": "Renewable Energy Promotion",
        "p56": "Women Empowerment & Safety Programs",
        "p57": "Child Nutrition & Midday Meal Improvement",
        "p58": "Skill Development & Vocational Training",
        "p59": "Rural Development & Irrigation Projects",
        "p60": "Support for Small Businesses & Startups",
        "p61": "Public Healthcare Expansion",
        "p62": "Digital Governance & e-Services Access",
        "p63": "Environmental Conservation Initiatives",
        "p64": "Transport & Road Modernization",
        "p65": "Arts, Culture & Heritage Promotion",
        "p66": "Senior Citizens Welfare Programs",
        "participants4": "Election Participants: 100 Candidates",
        "p67": "Local Employment Initiatives",
        "p68": "Education & Skill Training Programs",
        "p69": "Healthcare Expansion & Access",
        "p70": "Rural Infrastructure Development",
        "p71": "Affordable Housing for Communities",
        "p72": "Support for Small & Medium Enterprises (SMEs)",
        "p73": "Women & Child Welfare Programs",
        "p74": "Environmental Conservation Projects",
        "p75": "Digital Literacy & E-Governance Access",
        "p76": "Public Transport & Road Modernization",
        "p77": "Renewable Energy Initiatives",
        "p78": "Youth Empowerment & Vocational Training",
        "p79": "Community Development & Welfare Schemes",
        "p80": "Senior Citizens Welfare Programs",
        "p81": "Promotion of Arts, Culture & Heritage",
        "participants5": "Election Participants: 50 Candidates",
        "p82": "Regional Development Programs",
        "p83": "Fishermen Welfare Schemes",
        "p84": "Small Business Support",
        "p85": "Community Health Initiatives",
        "p86": "Local Education & Training",
        "p87": "Affordable Housing Projects",
        "p88": "Women & Child Welfare Programs",
        "p89": "Renewable Energy & Environmental Initiatives",
        "p90": "Rural Infrastructure Development",
        "p91": "Skill Development & Vocational Training",
        "p92": "Public Transport & Road Improvement",
        "participants6": "Election Participants: 30 Candidates",
        "p93": "Agriculture Support Programs",
        "p94": "Rural Infrastructure Development",
        "p95": "Youth Empowerment & Education",
        "p96": "Skill Development & Vocational Training",
        "p97": "Healthcare Access for Rural Communities",
        "p98": "Women & Child Welfare Programs",
        "p99": "Affordable Housing Schemes",
        "p100": "Small Business & Entrepreneurship Support",
        "p101": "Renewable Energy & Environmental Initiatives",
        "p102": "Public Transport & Road Modernization",
        "participants7": "Election Participants: 25 Candidates"
    
    },

    "hi": {
        "welcome": "ऑनलाइन वोटिंग में आपका स्वागत है",
        "tagline": "सुरक्षित • पारदर्शी • डिजिटल इंडिया",
        "vote": "अभी वोट करें",
        "gov": "भारत सरकार | ऑनलाइन वोटिंग सिस्टम",
        "home": "होम",
        "about": "परिचय",
        "service": "सेवाएं",
        "manifesto": "पार्टी घोषणा पत्र",
        "login": "लॉगिन",
        "title": "ऑनलाइन वोटिंग सिस्टम – भारत निर्वाचन आयोग",
        "ministry": "डिजिटल मामलों का मंत्रालय, भारत सरकार",
        "result": "परिणाम",
        "about_desc": "ऑनलाइन वोटिंग सिस्टम एक सुरक्षित डिजिटल प्लेटफॉर्म है जो नागरिकों को दूर से मतदान करने की सुविधा देता है। यह पारदर्शिता सुनिश्चित करता है, डुप्लिकेट वोटिंग को रोकता है और तुरंत चुनाव परिणाम प्रदान करता है।.",
        "about_title": "ऑनलाइन वोटिंग के बारे में",
        "features_title": "प्रमुख विशेषताएं",
        "secure_voting": "सुरक्षित मतदान",
        "auth_system": "उन्नत प्रमाणीकरण प्रणाली",
        "one_vote": "एक व्यक्ति एक वोट",
        "no_duplicate": "डुप्लिकेट वोट रोके जाते हैं",
        "instant_results": "त्वरित परिणाम",
        "live_count": "लाइव वोट गणना",
        "multi_lang": "बहुभाषी",
        "accessible": "सभी नागरिकों के लिए सुलभ",
        "stats": "चुनाव आँकड़े",
        "voters": "पंजीकृत मतदाता",
        "votes": "डाले गए वोट",
        "parties": "राजनीतिक दल",
        "how": "यह कैसे काम करता है",
        "step1": "वोटर आईडी के साथ पंजीकरण करें",
        "step2": "सुरक्षित लॉगिन करें",
        "step3": "अपनी पार्टी चुनें",
        "step4": "अपना वोट जमा करें",
        "step5": "चुनाव परिणाम देखें",
        "footer1": "ऑनलाइन वोटिंग सिस्टम",
        "footer2": "भारत निर्वाचन आयोग",
        "about_title_full": "ऑनलाइन वोटिंग सिस्टम के बारे में",
        "eci": "भारत निर्वाचन आयोग",
        "intro_title": "परिचय",
        "intro_desc": "ऑनलाइन वोटिंग सिस्टम एक डिजिटल प्लेटफॉर्म है जिसे चुनाव प्रक्रिया को आधुनिक बनाने के लिए विकसित किया गया है। यह नागरिकों को बिना मतदान केंद्र जाए कहीं से भी सुरक्षित रूप से वोट करने की अनुमति देता है।",
        "mission_title": "हमारा मिशन",
        "mission_desc": "हमारा मिशन मतदान को सभी के लिए सुलभ, पारदर्शी और सुरक्षित बनाना है। आधुनिक तकनीक के माध्यम से मतदाता भागीदारी बढ़ाना और निष्पक्ष चुनाव सुनिश्चित करना हमारा लक्ष्य है।",
        "security_title": "सुरक्षा और पारदर्शिता",
        "security_desc": "यह सिस्टम वोटर आईडी सत्यापन और प्रमाणीकरण का उपयोग करके डुप्लिकेट वोटिंग को रोकता है। प्रत्येक मतदाता केवल एक बार वोट कर सकता है।",
        "tech_title": "उपयोग की गई तकनीकें",
        "tech_desc": "यह सिस्टम Flask (Python), HTML, CSS, JavaScript और डेटाबेस तकनीकों का उपयोग करके गति, विश्वसनीयता और सुरक्षा सुनिश्चित करता है।",
        "benefits": "लाभ",
        "b1": "कहीं से भी वोट कर सकते हैं",
        "b2": "त्वरित परिणाम गणना",
        "b3": "पर्यावरण अनुकूल कागज रहित प्रणाली",
        "b4": "समय और लागत बचाता है",
        "back": "होम पेज पर वापस जाएं",
        "footer_main": "ऑनलाइन वोटिंग सिस्टम",
        "footer_gov": "भारत सरकार",
        "success": "आपका वोट सफलतापूर्वक जमा हो गया है!",
        "thanks": "वोट देने के लिए धन्यवाद।",
        "back": "होम पेज पर वापस जाएं",
        "reg_title": "मतदाता पंजीकरण",
        "reg_desc": "नागरिक वोटर आईडी और आधार विवरण का उपयोग करके ऑनलाइन पंजीकरण कर सकते हैं।",
        "login_title": "सुरक्षित लॉगिन",
        "login_desc": "मल्टी-लेवल प्रमाणीकरण प्रणाली सुरक्षित मतदाता पहुंच सुनिश्चित करती है।",
        "vote_title": "वोट डालें",
        "vote_desc": "मतदाता कहीं से भी डिजिटल रूप से वोट डाल सकते हैं।",
        "dup_title": "डुप्लिकेट वोट रोकथाम",
        "dup_desc": "सिस्टम एक ही मतदाता द्वारा कई बार वोट डालने से रोकता है।",
        "lang_title": "बहुभाषी समर्थन",
        "lang_desc": "क्षेत्रीय भाषाओं में उपलब्ध है ताकि सभी के लिए सुलभ हो।",
        "cand_title": "उम्मीदवार जानकारी",
        "cand_desc": "मतदान से पहले उम्मीदवार और पार्टी की जानकारी दिखाता है।",
        "live_title": "लाइव परिणाम",
        "live_desc": "त्वरित वोट गणना और पारदर्शी परिणाम प्रदर्शन।",
        "admin_title": "एडमिन निगरानी",
        "admin_desc": "चुनाव अधिकारी मतदान की निगरानी करते हैं और सिस्टम को प्रबंधित करते हैं।",
        "footer": "ऑनलाइन वोटिंग सिस्टम | भारत सरकार",
        "service_title": "हमारी सेवाएं",
        "eci": "भारत निर्वाचन आयोग",
        "manifesto_title": "पार्टी घोषणापत्र (कच्ची कोलकै)",
        "manifesto_sub": "चुनाव नीतियां एवं प्रतिभागियों का विवरण",
        "participants": "चुनाव प्रतिभागी: 120 उम्मीदवार",

        "p1": "मुफ्त शिक्षा योजना",
        "p2": "महिला सशक्तिकरण",
        "p3": "रोजगार सृजन कार्यक्रम",
        "p4": "सभी के लिए स्वास्थ्य सेवा",
        "p5": "पर्यावरणीय स्थिरता पहल",
        "p6": "सभी के लिए किफायती आवास",
        "p7": "ग्रामीण क्षेत्रों में डिजिटल साक्षरता और इंटरनेट पहुंच",
        "p8": "कला, संस्कृति और विरासत के लिए समर्थन",
        "p9": "नवीकरणीय ऊर्जा को बढ़ावा",
        "p10": "बाल पोषण और मध्यान्ह भोजन सुधार",
        "p11": "सार्वजनिक परिवहन विस्तार और आधुनिकीकरण",
        "p12": "भ्रष्टाचार विरोधी पारदर्शिता उपाय",
        "p13": "वरिष्ठ नागरिकों के लिए किफायती स्वास्थ्य सेवा",
        "p14": "कौशल विकास और व्यावसायिक प्रशिक्षण",
        "p15": "महिला सुरक्षा और कानूनी सहायता कार्यक्रम",
        "p16": "स्टार्टअप्स और छोटे व्यवसायों के लिए समर्थन",
        "p17": "शहरी हरित क्षेत्र और पार्क विकास",
        "p18": "डिजिटल शासन और ई-सेवाओं का विस्तार",
        "p19": "किसानों के लिए वित्तीय सहायता",
        "p20": "मुफ्त चिकित्सा शिविर",
        "p21": "ग्रामीण विकास",
        "p22": "महिला एवं बाल कल्याण कार्यक्रम",
        "p23": "शहरी अवसंरचना सुधार",
        "p24": "कम आय वाले परिवारों के लिए किफायती आवास",
        "p25": "स्वच्छ पेयजल परियोजनाएं",
        "p26": "नवीकरणीय ऊर्जा को बढ़ावा",
        "p27": "डिजिटल साक्षरता एवं ई-गवर्नेंस सुविधा",
        "p28": "सार्वजनिक स्वास्थ्य एवं टीकाकरण अभियान",
        "p29": "कौशल विकास एवं रोजगार कार्यक्रम",
        "p30": "परिवहन एवं सड़क आधुनिकीकरण",
        "p31": "लघु एवं मध्यम उद्योगों के लिए समर्थन",
        "p32": "पर्यावरण संरक्षण पहल",
        "p33": "वरिष्ठ नागरिक कल्याण कार्यक्रम",
        "p34": "बाल पोषण एवं मध्याह्न भोजन सुधार",
        "participants2": "चुनाव प्रतिभागी: 110 उम्मीदवार",
        "p35": "डिजिटल इंडिया विस्तार",
        "p36": "स्टार्टअप फंडिंग",
        "p37": "इन्फ्रास्ट्रक्चर विकास",
        "p38": "स्मार्ट सिटी परियोजनाएं",
        "p39": "कौशल विकास एवं व्यावसायिक प्रशिक्षण",
        "p40": "मेक इन इंडिया पहल",
        "p41": "नवीकरणीय ऊर्जा को बढ़ावा (सौर एवं पवन)",
        "p42": "सार्वजनिक परिवहन आधुनिकीकरण",
        "p43": "स्वास्थ्य सेवाएं एवं बीमा योजनाएं",
        "p44": "शिक्षा ऋण सहायता",
        "p45": "ग्रामीण विकास एवं सिंचाई परियोजनाएं",
        "p46": "लघु एवं मध्यम उद्यमों के लिए समर्थन (SMEs)",
        "p47": "महिला सशक्तिकरण कार्यक्रम",
        "p48": "शहरी हरित क्षेत्र एवं पार्क विकास",
        "p49": "भ्रष्टाचार विरोधी एवं शासन पारदर्शिता",
        "p50": "डिजिटल शासन एवं ई-सेवाओं का विस्तार",
        "participants3": "चुनाव प्रतिभागी: 95 उम्मीदवार",
        "p51": "युवा रोजगार योजना",
        "p52": "स्वास्थ्य बीमा",
        "p53": "शिक्षा ऋण माफी",
        "p54": "किफायती आवास योजनाएं",
        "p55": "नवीकरणीय ऊर्जा को बढ़ावा",
        "p56": "महिला सशक्तिकरण एवं सुरक्षा कार्यक्रम",
        "p57": "बाल पोषण और मध्यान्ह भोजन सुधार",
        "p58": "कौशल विकास एवं व्यावसायिक प्रशिक्षण",
        "p59": "ग्रामीण विकास एवं सिंचाई परियोजनाएं",
        "p60": "छोटे व्यवसायों एवं स्टार्टअप्स के लिए समर्थन",
        "p61": "सार्वजनिक स्वास्थ्य सेवाओं का विस्तार",
        "p62": "डिजिटल शासन एवं ई-सेवाओं की पहुंच",
        "p63": "पर्यावरण संरक्षण पहल",
        "p64": "परिवहन एवं सड़क आधुनिकीकरण",
        "p65": "कला, संस्कृति एवं विरासत प्रोत्साहन",
        "p66": "वरिष्ठ नागरिक कल्याण कार्यक्रम",
        "participants4": "चुनाव प्रतिभागी: 100 उम्मीदवार",
        "p67": "स्थानीय रोजगार पहल",
        "p68": "शिक्षा एवं कौशल प्रशिक्षण कार्यक्रम",
        "p69": "स्वास्थ्य सेवाओं का विस्तार एवं पहुंच",
        "p70": "ग्रामीण बुनियादी ढांचा विकास",
        "p71": "समुदायों के लिए किफायती आवास",
        "p72": "लघु एवं मध्यम उद्यमों के लिए समर्थन (SMEs)",
        "p73": "महिला एवं बाल कल्याण कार्यक्रम",
        "p74": "पर्यावरण संरक्षण परियोजनाएं",
        "p75": "डिजिटल साक्षरता एवं ई-गवर्नेंस पहुंच",
        "p76": "सार्वजनिक परिवहन एवं सड़क आधुनिकीकरण",
        "p77": "नवीकरणीय ऊर्जा पहल",
        "p78": "युवा सशक्तिकरण एवं व्यावसायिक प्रशिक्षण",
        "p79": "सामुदायिक विकास एवं कल्याण योजनाएं",
        "p80": "वरिष्ठ नागरिक कल्याण कार्यक्रम",
        "p81": "कला, संस्कृति एवं विरासत का प्रोत्साहन",
        "participants5": "चुनाव प्रतिभागी: 50 उम्मीदवार",
        "p82": "क्षेत्रीय विकास कार्यक्रम",
        "p83": "मछुआरा कल्याण योजनाएं",
        "p84": "छोटे व्यवसायों के लिए समर्थन",
        "p85": "सामुदायिक स्वास्थ्य पहल",
        "p86": "स्थानीय शिक्षा एवं प्रशिक्षण",
        "p87": "किफायती आवास परियोजनाएं",
        "p88": "महिला एवं बाल कल्याण कार्यक्रम",
        "p89": "नवीकरणीय ऊर्जा एवं पर्यावरण पहल",
        "p90": "ग्रामीण बुनियादी ढांचा विकास",
        "p91": "कौशल विकास एवं व्यावसायिक प्रशिक्षण",
        "p92": "सार्वजनिक परिवहन एवं सड़क सुधार",
        "participants6": "चुनाव प्रतिभागी: 30 उम्मीदवार",
        "p93": "कृषि समर्थन कार्यक्रम",
        "p94": "ग्रामीण बुनियादी ढांचा विकास",
        "p95": "युवा सशक्तिकरण एवं शिक्षा",
        "p96": "कौशल विकास एवं व्यावसायिक प्रशिक्षण",
        "p97": "ग्रामीण समुदायों के लिए स्वास्थ्य सेवाएं",
        "p98": "महिला एवं बाल कल्याण कार्यक्रम",
        "p99": "किफायती आवास योजनाएं",
        "p100": "छोटे व्यवसाय एवं उद्यमिता समर्थन",
        "p101": "नवीकरणीय ऊर्जा एवं पर्यावरण पहल",
        "p102": "सार्वजनिक परिवहन एवं सड़क आधुनिकीकरण",
        "participants7": "चुनाव प्रतिभागी: 25 उम्मीदवार"

    },

    "ta": {
        "welcome": "ஆன்லைன் வாக்குப்பதிவிற்கு வரவேற்கிறோம்",
        "tagline": "பாதுகாப்பான • வெளிப்படையான • டிஜிட்டல் இந்தியா",
        "vote": "வாக்களிக்கவும்",
        "gov": "இந்திய அரசு | ஆன்லைன் வாக்குப்பதிவு",
        "home": "முகப்பு",
        "about": "பற்றி",
        "service": "சேவைகள்",
        "manifesto": "கட்சிக் கொள்கை",
        "login": "உள்நுழை",
        "title": "ஆன்லைன் வாக்குப்பதிவு – இந்திய தேர்தல் ஆணையம்",
        "ministry": "டிஜிட்டல் விவகார அமைச்சகம், இந்திய அரசு",
        "about_title": "ஆன்லைன் வாக்குப்பதிவு பற்றி",
        "result": "முடிவு",
        "about_desc": "ஆன்லைன் வாக்குப்பதிவு முறை என்பது பாதுகாப்பான டிஜிட்டல் தளம் ஆகும். இது குடிமக்களுக்கு தூரத்தில் இருந்து வாக்களிக்க உதவுகிறது. இது வெளிப்படைத்தன்மையை உறுதி செய்கிறது, இரட்டை வாக்குகளை தவிர்க்கிறது மற்றும் உடனடி தேர்தல் முடிவுகளை வழங்குகிறது.",
        "features_title": "முக்கிய அம்சங்கள்",
        "secure_voting": "பாதுகாப்பான வாக்குப்பதிவு",
        "auth_system": "மேம்பட்ட அங்கீகார முறை",
        "one_vote": "ஒருவருக்கு ஒரு வாக்கு",
        "no_duplicate": "இரட்டை வாக்குகள் தடுக்கப்படும்",
        "instant_results": "உடனடி முடிவுகள்",
        "live_count": "நேரடி வாக்கு எண்ணிக்கை",
        "multi_lang": "பல மொழிகள்",
        "accessible": "அனைத்து குடிமக்களுக்கும் அணுகக்கூடியது",
        "stats": "தேர்தல் புள்ளிவிவரங்கள்",
        "voters": "பதிவு செய்யப்பட்ட வாக்காளர்கள்",
        "votes": "பதிவான வாக்குகள்",
        "parties": "அரசியல் கட்சிகள்",
        "how": "இது எப்படி செயல்படுகிறது",
        "step1": "வாக்காளர் அடையாள அட்டையுடன் பதிவு செய்யவும்",
        "step2": "பாதுகாப்பாக உள்நுழையவும்",
        "step3": "உங்கள் கட்சியை தேர்வு செய்யவும்",
        "step4": "உங்கள் வாக்கை சமர்ப்பிக்கவும்",
        "step5": "தேர்தல் முடிவுகளை பார்க்கவும்",
        "footer1": "ஆன்லைன் வாக்குப்பதிவு முறை",
        "footer2": "இந்திய தேர்தல் ஆணையம்",
        "about_title_full": "ஆன்லைன் வாக்குப்பதிவு முறையை பற்றி",
        "eci": "இந்திய தேர்தல் ஆணையம்",
        "intro_title": "அறிமுகம்",
        "intro_desc": "ஆன்லைன் வாக்குப்பதிவு முறை என்பது தேர்தல் செயல்முறையை நவீனமாக்க உருவாக்கப்பட்ட ஒரு டிஜிட்டல் தளம் ஆகும். இது குடிமக்கள் வாக்குச்சாவடிக்கு செல்லாமல் எங்கிருந்தும் பாதுகாப்பாக வாக்களிக்க அனுமதிக்கிறது.",
        "mission_title": "எங்கள் நோக்கம்",
        "mission_desc": "எங்கள் நோக்கம் வாக்குப்பதிவை அனைவருக்கும் எளிதாக அணுகக்கூடியதாக, வெளிப்படையானதாக மற்றும் பாதுகாப்பானதாக மாற்றுவது ஆகும். நவீன தொழில்நுட்பத்தின் மூலம் வாக்காளர் பங்கேற்பை அதிகரித்து, நியாயமான தேர்தல்களை உறுதி செய்வதே எங்கள் குறிக்கோள்.",
        "security_title": "பாதுகாப்பு மற்றும் வெளிப்படைத்தன்மை",
        "security_desc": "இந்த முறை வாக்காளர் அடையாளச் சரிபார்ப்பு மற்றும் அங்கீகாரத்தை பயன்படுத்தி இரட்டை வாக்குகளைத் தடுக்கும். ஒவ்வொரு வாக்காளரும் ஒருமுறை மட்டுமே வாக்களிக்க முடியும்.",
        "tech_title": "பயன்படுத்தப்பட்ட தொழில்நுட்பங்கள்",
        "tech_desc": "இந்த முறை Flask (Python), HTML, CSS, JavaScript மற்றும் தரவுத்தள தொழில்நுட்பங்களை பயன்படுத்தி வேகம், நம்பகத்தன்மை மற்றும் பாதுகாப்பை உறுதி செய்கிறது",
         "benefits": "நன்மைகள்",
        "b1": "எங்கிருந்தும் வாக்களிக்கலாம்",
        "b2": "உடனடி முடிவு கணக்கீடு",
        "b3": "சுற்றுச்சூழல் நட்பு காகிதமில்லா முறை",
        "b4": "நேரத்தையும் செலவையும் சேமிக்கிறது",
        "back": "முகப்புக்கு திரும்ப",
        "footer_main": "ஆன்லைன் வாக்குப்பதிவு முறை",
        "footer_gov": "இந்திய அரசு",
        "success": "உங்கள் வாக்கு வெற்றிகரமாக பதிவு செய்யப்பட்டது!",
        "thanks": "உங்கள் வாக்கை பதிவு செய்ததற்கு நன்றி.",
        "back": "முகப்புக்கு திரும்ப",
        "reg_title": "வாக்காளர் பதிவு",
        "reg_desc": "குடிமக்கள் வாக்காளர் அட்டை மற்றும் ஆதார் விவரங்களை பயன்படுத்தி ஆன்லைனில் பதிவு செய்யலாம்.",
        "login_title": "பாதுகாப்பான உள்நுழைவு",
        "login_desc": "பல நிலை அங்கீகார முறை பாதுகாப்பான வாக்காளர் அணுகலை உறுதி செய்கிறது.",
        "vote_title": "வாக்களிக்கவும்",
        "vote_desc": "வாக்காளர்கள் எங்கிருந்தும் டிஜிட்டல் முறையில் வாக்களிக்கலாம்.",
        "dup_title": "இரட்டை வாக்கு தடுப்பு",
        "dup_desc": "ஒரே வாக்காளர் பலமுறை வாக்களிப்பதை முறை தடுக்கிறது.",
        "lang_title": "பல மொழி ஆதரவு",
        "lang_desc": "அணுக எளிதாக பிராந்திய மொழிகளில் கிடைக்கிறது.",
        "cand_title": "வேட்பாளர் தகவல்",
        "cand_desc": "வாக்களிப்பதற்கு முன் வேட்பாளர் மற்றும் கட்சி விவரங்களை காட்டுகிறது.",
        "live_title": "நேரடி முடிவுகள்",
        "live_desc": "உடனடி வாக்கு எண்ணிக்கை மற்றும் வெளிப்படையான முடிவு காட்சி.",
        "admin_title": "நிர்வாக கண்காணிப்பு",
        "admin_desc": "தேர்தல் அதிகாரிகள் வாக்குப்பதிவை கண்காணித்து முறைமை நிர்வகிக்கிறார்கள்.",
        "footer": "ஆன்லைன் வாக்குப்பதிவு முறை | இந்திய அரசு",
        "service_title": "எங்கள் சேவைகள்",
        "eci": "இந்திய தேர்தல் ஆணையம்",
        "manifesto_title": "கட்சி அறிக்கை (கட்சிக் கொள்கை)",
        "manifesto_sub": "தேர்தல் கொள்கைகள் மற்றும் பங்கேற்பாளர் விவரங்கள்",
        "participants": "தேர்தல் பங்கேற்பாளர்கள்: 120 வேட்பாளர்கள்",

        "p1": "இலவச கல்வி திட்டம்",
        "p2": "பெண்கள் அதிகாரமளித்தல்",
        "p3": "வேலை வாய்ப்பு உருவாக்க திட்டங்கள்",
        "p4": "அனைவருக்கும் சுகாதார சேவை",
        "p5": "சுற்றுச்சூழல் நிலைத்தன்மை முயற்சிகள்",
        "p6": "அனைவருக்கும் மலிவு வீடுகள்",
        "p7": "கிராமப்புறங்களில் டிஜிட்டல் கல்வி மற்றும் இணைய அணுகல்",
        "p8": "கலை, கலாசாரம் மற்றும் பாரம்பரியத்திற்கு ஆதரவு",
        "p9": "புதுப்பிக்கத்தக்க ஆற்றல் ஊக்குவிப்பு",
        "p10": "குழந்தை ஊட்டச்சத்து மற்றும் மதிய உணவு மேம்பாடு",
        "p11": "பொதுப் போக்குவரத்து விரிவாக்கம் மற்றும் நவீனமயம்",
        "p12": "ஊழல் எதிர்ப்பு மற்றும் வெளிப்படைத்தன்மை நடவடிக்கைகள்",
        "p13": "முதியோருக்கான மலிவு சுகாதாரம்",
        "p14": "திறன் மேம்பாடு மற்றும் தொழில் பயிற்சி",
        "p15": "பெண்கள் பாதுகாப்பு மற்றும் சட்ட உதவி திட்டங்கள்",
        "p16": "தொடக்க நிறுவனங்கள் மற்றும் சிறு தொழில்களுக்கு ஆதரவு",
        "p17": "நகர பசுமை பகுதிகள் மற்றும் பூங்கா மேம்பாடு",
        "p18": "டிஜிட்டல் நிர்வாகம் மற்றும் மின் சேவைகள் விரிவாக்கம்",
        "p19": "விவசாயிகளுக்கான நிதி ஆதரவு",
        "p20": "இலவச மருத்துவ முகாம்கள்",
        "p21": "கிராமப்புற வளர்ச்சி",
        "p22": "பெண்கள் மற்றும் குழந்தைகள் நல திட்டங்கள்",
        "p23": "நகர உள்கட்டமைப்பு மேம்பாடு",
        "p24": "குறைந்த வருமான குடும்பங்களுக்கு மலிவு வீடுகள்",
        "p25": "தூய குடிநீர் திட்டங்கள்",
        "p26": "புதுப்பிக்கத்தக்க ஆற்றல் ஊக்குவிப்பு",
        "p27": "டிஜிட்டல் கல்வி மற்றும் மின் ஆட்சி அணுகல்",
        "p28": "பொதுச் சுகாதாரம் மற்றும் தடுப்பூசி முகாம்கள்",
        "p29": "திறன் மேம்பாடு மற்றும் வேலைவாய்ப்பு திட்டங்கள்",
        "p30": "போக்குவரத்து மற்றும் சாலை நவீனமயம்",
        "p31": "சிறு மற்றும் நடுத்தர தொழில்களுக்கு ஆதரவு",
        "p32": "சுற்றுச்சூழல் பாதுகாப்பு முயற்சிகள்",
        "p33": "முதியோர் நல திட்டங்கள்",
        "p34": "குழந்தை ஊட்டச்சத்து மற்றும் மதிய உணவு மேம்பாடு",
        "participants2": "தேர்தல் பங்கேற்பாளர்கள்: 110 வேட்பாளர்கள்",
        "p35": "டிஜிட்டல் இந்தியா விரிவாக்கம்",
        "p36": "ஸ்டார்ட்அப் நிதியுதவி",
        "p37": "மூலவள வளர்ச்சி",
        "p38": "ஸ்மார்ட் சிட்டி திட்டங்கள்",
        "p39": "திறன் மேம்பாடு & தொழில் பயிற்சி",
        "p40": "மேக் இன் இந்தியா முயற்சிகள்",
        "p41": "புதுப்பிக்கத்தக்க ஆற்றல் ஊக்குவிப்பு (சூரிய & காற்றாலை)",
        "p42": "பொது போக்குவரத்து நவீனமயம்",
        "p43": "சுகாதார சேவைகள் & காப்பீட்டு திட்டங்கள்",
        "p44": "கல்வி கடன் உதவி",
        "p45": "கிராமப்புற வளர்ச்சி & பாசன திட்டங்கள்",
        "p46": "சிறு & நடுத்தர தொழில்களுக்கு ஆதரவு (SMEs)",
        "p47": "பெண்கள் அதிகாரமளித்தல் திட்டங்கள்",
        "p48": "நகர பசுமை பகுதிகள் & பூங்கா மேம்பாடு",
        "p49": "ஊழல் எதிர்ப்பு & நிர்வாக வெளிப்படைத்தன்மை",
        "p50": "டிஜிட்டல் நிர்வாகம் & மின் சேவைகள் விரிவாக்கம்",
        "participants3": "தேர்தல் பங்கேற்பாளர்கள்: 95 வேட்பாளர்கள்",
        "p51": "இளைஞர் வேலைவாய்ப்பு திட்டம்",
        "p52": "சுகாதார காப்பீடு",
        "p53": "கல்வி கடன் தள்ளுபடி",
        "p54": "மலிவு வீட்டு திட்டங்கள்",
        "p55": "புதுப்பிக்கத்தக்க ஆற்றல் ஊக்குவிப்பு",
        "p56": "பெண்கள் அதிகாரமளித்தல் & பாதுகாப்பு திட்டங்கள்",
        "p57": "குழந்தை ஊட்டச்சத்து மற்றும் மதிய உணவு மேம்பாடு",
        "p58": "திறன் மேம்பாடு & தொழில் பயிற்சி",
        "p59": "கிராமப்புற வளர்ச்சி & பாசன திட்டங்கள்",
        "p60": "சிறு தொழில்கள் & ஸ்டார்ட்அப் நிறுவனங்களுக்கு ஆதரவு",
        "p61": "பொது சுகாதார சேவைகள் விரிவாக்கம்",
        "p62": "டிஜிட்டல் நிர்வாகம் & மின் சேவைகள் அணுகல்",
        "p63": "சுற்றுச்சூழல் பாதுகாப்பு முயற்சிகள்",
        "p64": "போக்குவரத்து & சாலை நவீனமயம்",
        "p65": "கலை, கலாசாரம் & பாரம்பரிய ஊக்குவிப்பு",
        "p66": "முதியோர் நல திட்டங்கள்",
        "participants4": "தேர்தல் பங்கேற்பாளர்கள்: 100 வேட்பாளர்கள்",
        "p67": "உள்ளூர் வேலைவாய்ப்பு முயற்சிகள்",
        "p68": "கல்வி & திறன் பயிற்சி திட்டங்கள்",
        "p69": "சுகாதார சேவைகள் விரிவாக்கம் & அணுகல்",
        "p70": "கிராமப்புற அடிப்படை வசதி மேம்பாடு",
        "p71": "சமூகங்களுக்கு மலிவு வீடுகள்",
        "p72": "சிறு & நடுத்தர தொழில்களுக்கு ஆதரவு (SMEs)",
        "p73": "பெண்கள் & குழந்தைகள் நல திட்டங்கள்",
        "p74": "சுற்றுச்சூழல் பாதுகாப்பு திட்டங்கள்",
        "p75": "டிஜிட்டல் கல்வி & மின் நிர்வாக அணுகல்",
        "p76": "பொது போக்குவரத்து & சாலை நவீனமயம்",
        "p77": "புதுப்பிக்கத்தக்க ஆற்றல் முயற்சிகள்",
        "p78": "இளைஞர் அதிகாரமளித்தல் & தொழில் பயிற்சி",
        "p79": "சமூக வளர்ச்சி & நல திட்டங்கள்",
        "p80": "முதியோர் நல திட்டங்கள்",
        "p81": "கலை, கலாசாரம் & பாரம்பரிய ஊக்குவிப்பு",
        "participants5": "தேர்தல் பங்கேற்பாளர்கள்: 50 வேட்பாளர்கள்",
        "p82": "மண்டல வளர்ச்சி திட்டங்கள்",
        "p83": "மீனவர் நல திட்டங்கள்",
        "p84": "சிறு தொழில்களுக்கு ஆதரவு",
        "p85": "சமூக சுகாதார முயற்சிகள்",
        "p86": "உள்ளூர் கல்வி & பயிற்சி",
        "p87": "மலிவு வீட்டு திட்டங்கள்",
        "p88": "பெண்கள் & குழந்தைகள் நல திட்டங்கள்",
        "p89": "புதுப்பிக்கத்தக்க ஆற்றல் & சுற்றுச்சூழல் முயற்சிகள்",
        "p90": "கிராமப்புற அடிப்படை வசதி மேம்பாடு",
        "p91": "திறன் மேம்பாடு & தொழில் பயிற்சி",
        "p92": "பொது போக்குவரத்து & சாலை மேம்பாடு",
        "participants6": "தேர்தல் பங்கேற்பாளர்கள்: 30 வேட்பாளர்கள்",
        "p93": "விவசாய ஆதரவு திட்டங்கள்",
        "p94": "கிராமப்புற அடிப்படை வசதி மேம்பாடு",
        "p95": "இளைஞர் அதிகாரமளித்தல் & கல்வி",
        "p96": "திறன் மேம்பாடு & தொழில் பயிற்சி",
        "p97": "கிராமப்புறங்களுக்கு சுகாதார சேவைகள்",
        "p98": "பெண்கள் & குழந்தைகள் நல திட்டங்கள்",
        "p99": "மலிவு வீட்டு திட்டங்கள்",
        "p100": "சிறு தொழில் & தொழில் தொடக்க ஆதரவு",
        "p101": "புதுப்பிக்கத்தக்க ஆற்றல் & சுற்றுச்சூழல் முயற்சிகள்",
        "p102": "பொது போக்குவரத்து & சாலை நவீனமயம்",
        "participants7": "தேர்தல் பங்கேற்பாளர்கள்: 25 வேட்பாளர்கள்"
    },

    "te": {
        "welcome": "ఆన్‌లైన్ ఓటింగ్‌కు స్వాగతం",
        "tagline": "సురక్షిత • పారదర్శక • డిజిటల్ ఇండియా",
        "vote": "ఇప్పుడే ఓటు వేయండి",
        "gov": "భారత ప్రభుత్వం | ఆన్‌లైన్ ఓటింగ్",
        "home": "హోమ్",
        "about": "గురించి",
        "service": "సేవలు",
        "manifesto": "పార్టీ మేనిఫెస్టో",
        "login": "లాగిన్",
        "title": "ఆన్‌లైన్ ఓటింగ్ – భారత ఎన్నికల సంఘం",
        "ministry": "డిజిటల్ వ్యవహారాల మంత్రిత్వ శాఖ, భారత ప్రభుత్వం",
        "result": "ఫలితం",
        "about_desc": "ఆన్‌లైన్ ఓటింగ్ సిస్టమ్ ఒక సురక్షిత డిజిటల్ వేదిక. ఇది పౌరులు దూరం నుండి ఓటు వేయడానికి సహాయపడుతుంది. ఇది పారదర్శకతను నిర్ధారిస్తుంది, డూప్లికేట్ ఓట్లను నివారిస్తుంది మరియు తక్షణ ఎన్నికల ఫలితాలను అందిస్తుంది.",
        "about_title": "ఆన్‌లైన్ ఓటింగ్ గురించి",
        "features_title": "ముఖ్య లక్షణాలు",
        "secure_voting": "సురక్షిత ఓటింగ్",
        "auth_system": "ఆధునిక ప్రమాణీకరణ వ్యవస్థ",
        "one_vote": "ఒక్క వ్యక్తికి ఒక ఓటు",
        "no_duplicate": "డూప్లికేట్ ఓట్లు నిరోధించబడతాయి",
        "instant_results": "తక్షణ ఫలితాలు",
        "live_count": "ప్రత్యక్ష ఓట్ల లెక్కింపు",
        "multi_lang": "బహుభాషా",
        "accessible": "అన్ని పౌరులకు అందుబాటులో ఉంటుంది",
        "stats": "ఎన్నికల గణాంకాలు",
        "voters": "నమోదు చేసిన ఓటర్లు",
        "votes": "వేసిన ఓట్లు",
        "parties": "రాజకీయ పార్టీలు",
        "how": "ఇది ఎలా పనిచేస్తుంది",
        "step1": "ఓటర్ ఐడితో నమోదు చేసుకోండి",
        "step2": "సురక్షితంగా లాగిన్ అవ్వండి",
        "step3": "మీ పార్టీని ఎంచుకోండి",
        "step4": "మీ ఓటును సమర్పించండి",
        "step5": "ఎన్నికల ఫలితాలను చూడండి",
        "footer1": "ఆన్‌లైన్ ఓటింగ్ సిస్టమ్",
        "footer2": "భారత ఎన్నికల కమిషన్",
        "about_title_full": "ఆన్‌లైన్ ఓటింగ్ సిస్టమ్ గురించి",
        "eci": "భారత ఎన్నికల కమిషన్",
        "intro_title": "పరిచయం",
        "intro_desc": "ఆన్‌లైన్ ఓటింగ్ సిస్టమ్ ఎన్నికల ప్రక్రియను ఆధునికీకరించడానికి రూపొందించిన ఒక డిజిటల్ వేదిక. ఇది పౌరులు పోలింగ్ బూత్‌లకు వెళ్లకుండా ఎక్కడి నుండైనా సురక్షితంగా ఓటు వేయడానికి అనుమతిస్తుంది.",
        "mission_title": "మా లక్ష్యం",
        "mission_desc": "మా లక్ష్యం ఓటింగ్‌ను అందరికీ సులభంగా అందుబాటులో ఉండేలా, పారదర్శకంగా మరియు సురక్షితంగా చేయడం. ఆధునిక సాంకేతికత ద్వారా ఓటర్ల పాల్గొనడం పెంచి, న్యాయమైన ఎన్నికలను నిర్ధారించడం.",
        "security_title": "భద్రత & పారదర్శకత",
        "security_desc": "ఈ వ్యవస్థ ఓటర్ ఐడి ధృవీకరణ మరియు ప్రమాణీకరణను ఉపయోగించి డూప్లికేట్ ఓట్లను నివారిస్తుంది. ప్రతి ఓటరు ఒక్కసారి మాత్రమే ఓటు వేయగలరు.",
        "tech_title": "ఉపయోగించిన సాంకేతికతలు",
        "tech_desc": "ఈ వ్యవస్థ Flask (Python), HTML, CSS, JavaScript మరియు డేటాబేస్ సాంకేతికతలను ఉపయోగించి వేగం, విశ్వసనీయత మరియు భద్రతను ապահովిస్తుంది.",
        "benefits": "ప్రయోజనాలు",
        "b1": "ఎక్కడి నుండైనా ఓటు వేయవచ్చు",
        "b2": "తక్షణ ఫలిత లెక్కింపు",
        "b3": "పర్యావరణ హిత కాగితం రహిత వ్యవస్థ",
        "b4": "సమయం మరియు ఖర్చు ఆదా చేస్తుంది",
        "back": "హోమ్‌కు తిరిగి వెళ్లండి",
        "footer_main": "ఆన్‌లైన్ ఓటింగ్ సిస్టమ్",
        "footer_gov": "భారత ప్రభుత్వం",
        "success": "మీ ఓటు విజయవంతంగా సమర్పించబడింది!",
        "thanks": "మీ ఓటు వేసినందుకు ధన్యవాదాలు.",
        "back": "హోమ్‌కు తిరిగి వెళ్లండి",
        "reg_title": "ఓటర్ నమోదు",
        "reg_desc": "పౌరులు ఓటర్ ఐడి మరియు ఆధార్ వివరాలను ఉపయోగించి ఆన్‌లైన్‌లో నమోదు చేసుకోవచ్చు.",
        "login_title": "సురక్షిత లాగిన్",
        "login_desc": "బహుస్థాయి ప్రమాణీకరణ వ్యవస్థ సురక్షిత ఓటర్ ప్రవేశాన్ని నిర్ధారిస్తుంది.",
        "vote_title": "ఓటు వేయండి",
        "vote_desc": "ఓటర్లు ఎక్కడి నుండైనా డిజిటల్‌గా ఓటు వేయవచ్చు.",
         "dup_title": "డూప్లికేట్ ఓటు నివారణ",
        "dup_desc": "ఒకే ఓటరు పలుమార్లు ఓటు వేయకుండా వ్యవస్థ అడ్డుకుంటుంది.",
        "lang_title": "బహుభాషా మద్దతు",
        "lang_desc": "సులభతరం కోసం ప్రాంతీయ భాషల్లో అందుబాటులో ఉంది.",
        "cand_title": "అభ్యర్థి సమాచారం",
        "cand_desc": "ఓటు వేయడానికి ముందు అభ్యర్థి మరియు పార్టీ వివరాలు చూపిస్తుంది.",
        "live_title": "ప్రత్యక్ష ఫలితాలు",
        "live_desc": "తక్షణ ఓట్ల లెక్కింపు మరియు పారదర్శక ఫలిత ప్రదర్శన.",
        "admin_title": "అడ్మిన్ పర్యవేక్షణ",
        "admin_desc": "ఎన్నికల అధికారులు ఓటింగ్‌ను పర్యవేక్షించి వ్యవస్థను నిర్వహిస్తారు.",
        "footer": "ఆన్‌లైన్ ఓటింగ్ సిస్టమ్ | భారత ప్రభుత్వం",
        "service_title": "మా సేవలు",
        "eci": "భారత ఎన్నికల కమిషన్",
        "manifesto_title": "పార్టీ మేనిఫెస్టో (కచ్చి కొల్కై)",
        "manifesto_sub": "ఎన్నికల విధానాలు & పాల్గొనేవారి వివరాలు",
        "participants": "ఎన్నికల పాల్గొనేవారు: 120 అభ్యర్థులు",

        "p1": "ఉచిత విద్యా పథకం",
        "p2": "మహిళా సాధికారత",
        "p3": "ఉద్యోగ సృష్టి కార్యక్రమాలు",
        "p4": "అందరికీ ఆరోగ్య సేవలు",
        "p5": "పర్యావరణ స్థిరత్వ చర్యలు",
        "p6": "అందరికీ అందుబాటు గృహాలు",
        "p7": "గ్రామీణ ప్రాంతాల్లో డిజిటల్ సాక్షరత మరియు ఇంటర్నెట్ ప్రాప్తి",
        "p8": "కళలు, సంస్కృతి & వారసత్వానికి మద్దతు",
        "p9": "పునరుత్పాదక శక్తి ప్రోత్సాహం",
        "p10": "పిల్లల పోషణ మరియు మధ్యాహ్న భోజన మెరుగుదల",
        "p11": "ప్రజా రవాణా విస్తరణ & ఆధునీకరణ",
        "p12": "అవినీతి వ్యతిరేక పారదర్శక చర్యలు",
        "p13": "వృద్ధులకు అందుబాటు ఆరోగ్య సేవలు",
        "p14": "నైపుణ్యాభివృద్ధి & వృత్తి శిక్షణ",
        "p15": "మహిళల భద్రత & న్యాయ సహాయం కార్యక్రమాలు",
        "p16": "స్టార్టప్‌లు మరియు చిన్న వ్యాపారాలకు మద్దతు",
        "p17": "నగర పచ్చని ప్రదేశాలు & పార్కుల అభివృద్ధి",
        "p18": "డిజిటల్ పరిపాలన & ఈ-సేవల విస్తరణ",
        "p19": "రైతులకు ఆర్థిక సహాయం",
        "p20": "ఉచిత వైద్య శిబిరాలు",
        "p21": "గ్రామీణ అభివృద్ధి",
        "p22": "మహిళలు & పిల్లల సంక్షేమ కార్యక్రమాలు",
        "p23": "పట్టణ మౌలిక వసతుల మెరుగుదల",
        "p24": "తక్కువ ఆదాయం కల కుటుంబాలకు అందుబాటు గృహాలు",
        "p25": "స్వచ్ఛమైన తాగునీటి ప్రాజెక్టులు",
        "p26": "పునరుత్పాదక శక్తి ప్రోత్సాహం",
        "p27": "డిజిటల్ విద్య & ఈ-పాలన సేవల ప్రాప్తి",
        "p28": "ప్రజా ఆరోగ్యం & టీకా కార్యక్రమాలు",
        "p29": "నైపుణ్యాభివృద్ధి & ఉపాధి కార్యక్రమాలు",
        "p30": "రవాణా & రహదారి ఆధునీకరణ",
        "p31": "చిన్న & మధ్య తరహా పరిశ్రమలకు మద్దతు",
        "p32": "పర్యావరణ పరిరక్షణ కార్యక్రమాలు",
        "p33": "వృద్ధుల సంక్షేమ కార్యక్రమాలు",
        "p34": "పిల్లల పోషణ & మధ్యాహ్న భోజన మెరుగుదల",
        "participants2": "ఎన్నికల పాల్గొనేవారు: 110 అభ్యర్థులు",
        "p35": "డిజిటల్ ఇండియా విస్తరణ",
        "p36": "స్టార్టప్ నిధులు",
        "p37": "మౌలిక వసతుల అభివృద్ధి",
        "p38": "స్మార్ట్ సిటీ ప్రాజెక్టులు",
        "p39": "నైపుణ్యాభివృద్ధి & వృత్తి శిక్షణ",
        "p40": "మేక్ ఇన్ ఇండియా కార్యక్రమాలు",
        "p41": "పునరుత్పాదక శక్తి ప్రోత్సాహం (సౌర & గాలి)",
        "p42": "ప్రజా రవాణా ఆధునీకరణ",
        "p43": "ఆరోగ్య సేవలు & బీమా పథకాలు",
        "p44": "విద్యా రుణ సహాయం",
        "p45": "గ్రామీణ అభివృద్ధి & సాగునీటి ప్రాజెక్టులు",
        "p46": "చిన్న మరియు మధ్య తరహా సంస్థలకు మద్దతు (SMEs)",
        "p47": "మహిళా సాధికారత కార్యక్రమాలు",
        "p48": "నగర పచ్చని ప్రదేశాలు & పార్కుల అభివృద్ధి",
        "p49": "అవినీతి నిరోధం & పరిపాలన పారదర్శకత",
        "p50": "డిజిటల్ పరిపాలన & ఈ-సేవల విస్తరణ",
        "participants3": "ఎన్నికల పాల్గొనేవారు: 95 అభ్యర్థులు",
        "p51": "యువ ఉద్యోగ ప్రణాళిక",
        "p52": "ఆరోగ్య బీమా",
        "p53": "విద్యా రుణ మాఫీ",
        "p54": "అందుబాటు గృహ పథకాలు",
        "p55": "పునరుత్పాదక శక్తి ప్రోత్సాహం",
        "p56": "మహిళా సాధికారత & భద్రతా కార్యక్రమాలు",
        "p57": "పిల్లల పోషణ మరియు మధ్యాహ్న భోజన మెరుగుదల",
        "p58": "నైపుణ్యాభివృద్ధి & వృత్తి శిక్షణ",
        "p59": "గ్రామీణ అభివృద్ధి & సాగునీటి ప్రాజెక్టులు",
        "p60": "చిన్న వ్యాపారాలు & స్టార్టప్‌లకు మద్దతు",
        "p61": "ప్రజా ఆరోగ్య సేవల విస్తరణ",
        "p62": "డిజిటల్ పరిపాలన & ఈ-సేవల ప్రాప్తి",
        "p63": "పర్యావరణ పరిరక్షణ చర్యలు",
        "p64": "రవాణా & రహదారి ఆధునీకరణ",
        "p65": "కళలు, సంస్కృతి & వారసత్వ ప్రోత్సాహం",
        "p66": "వృద్ధుల సంక్షేమ కార్యక్రమాలు",
        "participants4": "ఎన్నికల పాల్గొనేవారు: 100 అభ్యర్థులు",
        "p67": "స్థానిక ఉపాధి కార్యక్రమాలు",
        "p68": "విద్య & నైపుణ్య శిక్షణ కార్యక్రమాలు",
        "p69": "ఆరోగ్య సేవల విస్తరణ & ప్రాప్తి",
        "p70": "గ్రామీణ మౌలిక వసతుల అభివృద్ధి",
        "p71": "సమాజాలకు అందుబాటు గృహాలు",
        "p72": "చిన్న & మధ్య తరహా సంస్థలకు మద్దతు (SMEs)",
        "p73": "మహిళలు & పిల్లల సంక్షేమ కార్యక్రమాలు",
        "p74": "పర్యావరణ పరిరక్షణ ప్రాజెక్టులు",
        "p75": "డిజిటల్ సాక్షరత & ఈ-గవర్నెన్స్ ప్రాప్తి",
        "p76": "ప్రజా రవాణా & రహదారి ఆధునీకరణ",
        "p77": "పునరుత్పాదక శక్తి కార్యక్రమాలు",
        "p78": "యువ సాధికారత & వృత్తి శిక్షణ",
        "p79": "సమాజ అభివృద్ధి & సంక్షేమ పథకాలు",
        "p80": "వృద్ధుల సంక్షేమ కార్యక్రమాలు",
        "p81": "కళలు, సంస్కృతి & వారసత్వ ప్రోత్సాహం",
        "participants5": "ఎన్నికల పాల్గొనేవారు: 50 అభ్యర్థులు",
        "p82": "ప్రాంతీయ అభివృద్ధి కార్యక్రమాలు",
        "p83": "మత్స్యకారుల సంక్షేమ పథకాలు",
        "p84": "చిన్న వ్యాపారాలకు మద్దతు",
        "p85": "సమాజ ఆరోగ్య కార్యక్రమాలు",
        "p86": "స్థానిక విద్య & శిక్షణ",
        "p87": "అందుబాటు గృహ ప్రాజెక్టులు",
        "p88": "మహిళలు & పిల్లల సంక్షేమ కార్యక్రమాలు",
        "p89": "పునరుత్పాదక శక్తి & పర్యావరణ కార్యక్రమాలు",
        "p90": "గ్రామీణ మౌలిక వసతుల అభివృద్ధి",
        "p91": "నైపుణ్యాభివృద్ధి & వృత్తి శిక్షణ",
        "p92": "ప్రజా రవాణా & రహదారి మెరుగుదల",
        "participants6": "ఎన్నికల పాల్గొనేవారు: 30 అభ్యర్థులు",
        "p93": "వ్యవసాయ మద్దతు కార్యక్రమాలు",
        "p94": "గ్రామీణ మౌలిక వసతుల అభివృద్ధి",
        "p95": "యువ సాధికారత & విద్య",
        "p96": "నైపుణ్యాభివృద్ధి & వృత్తి శిక్షణ",
        "p97": "గ్రామీణ ప్రాంతాలకు ఆరోగ్య సేవలు",
        "p98": "మహిళలు & పిల్లల సంక్షేమ కార్యక్రమాలు",
        "p99": "అందుబాటు గృహ పథకాలు",
        "p100": "చిన్న వ్యాపారాలు & వ్యాపారారంభ మద్దతు",
        "p101": "పునరుత్పాదక శక్తి & పర్యావరణ కార్యక్రమాలు",
        "p102": "ప్రజా రవాణా & రహదారి ఆధునీకరణ",
        "participants7": "ఎన్నికల పాల్గొనేవారు: 25 అభ్యర్థులు"
    
    },

    "ml": {
        "welcome": "ഓൺലൈൻ വോട്ടിംഗിലേക്ക് സ്വാഗതം",
        "tagline": "സുരക്ഷിത • സുതാര്യ • ഡിജിറ്റൽ ഇന്ത്യ",
        "vote": "വോട്ട് ചെയ്യുക",
        "gov": "ഇന്ത്യ സർക്കാർ | ഓൺലൈൻ വോട്ടിംഗ്",
        "home": "ഹോം",
        "about": "കുറിച്ച്",
        "service": "സേവനങ്ങൾ",
        "manifesto": "പാർട്ടി പ്രഖ്യാപനം",
        "login": "ലോഗിൻ",
        "title": "ഓൺലൈൻ വോട്ടിംഗ് – ഇന്ത്യ തിരഞ്ഞെടുപ്പ് കമ്മീഷൻ",
        "ministry": "ഡിജിറ്റൽ കാര്യ മന്ത്രാലയം, ഇന്ത്യ സർക്കാർ",
        "result": "ഫലം",
        "about_desc": "ഓൺലൈൻ വോട്ടിംഗ് സിസ്റ്റം ഒരു സുരക്ഷിതമായ ഡിജിറ്റൽ പ്ലാറ്റ്‌ഫോമാണ്. ഇത് പൗരന്മാർക്ക് ദൂരസ്ഥമായി വോട്ട് ചെയ്യാൻ സഹായിക്കുന്നു. ഇത് സുതാര്യത ഉറപ്പാക്കുന്നു, ഇരട്ട വോട്ടുകൾ ഒഴിവാക്കുന്നു, ഉടൻ തെരഞ്ഞെടുപ്പ് ഫലങ്ങൾ നൽകുന്നു.",
        "about_title": "ഓൺലൈൻ വോട്ടിംഗ് കുറിച്ച്",
        "features_title": "പ്രധാന സവിശേഷതകൾ",
        "secure_voting": "സുരക്ഷിത വോട്ടിംഗ്",
        "auth_system": "ആധുനിക സ്ഥിരീകരണ സംവിധാനം",
        "one_vote": "ഒരാൾക്ക് ഒരു വോട്ട്",
        "no_duplicate": "ഇരട്ട വോട്ടുകൾ തടയപ്പെടും",
        "instant_results": "തത്സമയം ഫലങ്ങൾ",
        "live_count": "തത്സമയ വോട്ട് എണ്ണൽ",
        "multi_lang": "ബഹുഭാഷ",
        "accessible": "എല്ലാ പൗരന്മാർക്കും ലഭ്യമാണ്",
        "stats": "തിരഞ്ഞെടുപ്പ് സ്ഥിതിവിവരക്കണക്കുകൾ",
        "voters": "രജിസ്റ്റർ ചെയ്ത വോട്ടർമാർ",
        "votes": "രേഖപ്പെടുത്തിയ വോട്ടുകൾ",
        "parties": "രാഷ്ട്രീയ പാർട്ടികൾ",
        "how": "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു",
        "step1": "വോട്ടർ ഐഡിയോടെ രജിസ്റ്റർ ചെയ്യുക",
        "step2": "സുരക്ഷിതമായി ലോഗിൻ ചെയ്യുക",
        "step3": "നിങ്ങളുടെ പാർട്ടി തിരഞ്ഞെടുക്കുക",
        "step4": "നിങ്ങളുടെ വോട്ട് സമർപ്പിക്കുക",
        "step5": "തിരഞ്ഞെടുപ്പ് ഫലങ്ങൾ കാണുക",
        "footer1": "ഓൺലൈൻ വോട്ടിംഗ് സിസ്റ്റം",
        "footer2": "ഇന്ത്യൻ തിരഞ്ഞെടുപ്പ് കമ്മീഷൻ",
        "about_title_full": "ഓൺലൈൻ വോട്ടിംഗ് സിസ്റ്റത്തെ കുറിച്ച്",
        "eci": "ഇന്ത്യൻ തിരഞ്ഞെടുപ്പ് കമ്മീഷൻ",
        "intro_title": "പരിചയം",
        "intro_desc": "ഓൺലൈൻ വോട്ടിംഗ് സിസ്റ്റം തിരഞ്ഞെടുപ്പ് പ്രക്രിയയെ ആധുനികമാക്കാൻ വികസിപ്പിച്ച ഒരു ഡിജിറ്റൽ പ്ലാറ്റ്‌ഫോമാണ്. ഇത് പൗരന്മാർക്ക് പോളിംഗ് ബൂത്തിലേക്ക് പോകാതെ എവിടെയും നിന്ന് സുരക്ഷിതമായി വോട്ട് ചെയ്യാൻ അനുവദിക്കുന്നു.",
        "mission_title": "ഞങ്ങളുടെ ദൗത്യം",
        "mission_desc": "വോട്ടിംഗ് എല്ലാവർക്കും എളുപ്പത്തിൽ ലഭ്യമാകുകയും, സുതാര്യവും സുരക്ഷിതവും ആക്കുക എന്നതാണ് ഞങ്ങളുടെ ദൗത്യം. ആധുനിക സാങ്കേതിക വിദ്യ ഉപയോഗിച്ച് വോട്ടർമാരുടെ പങ്കാളിത്തം വർധിപ്പിക്കുകയും ന്യായമായ തിരഞ്ഞെടുപ്പുകൾ ഉറപ്പാക്കുകയും ചെയ്യുകയാണ് ലക്ഷ്യം.",
        "security_title": "സുരക്ഷയും സുതാര്യതയും",
        "security_desc": "ഈ സംവിധാനം വോട്ടർ ഐഡി പരിശോധനയും സ്ഥിരീകരണവും ഉപയോഗിച്ച് ഇരട്ട വോട്ടിംഗ് തടയുന്നു. ഓരോ വോട്ടർക്കും ഒരിക്കൽ മാത്രം വോട്ട് ചെയ്യാം.",
        "tech_title": "ഉപയോഗിച്ച സാങ്കേതികവിദ്യകൾ",
        "tech_desc": "ഈ സംവിധാനം Flask (Python), HTML, CSS, JavaScript, ഡാറ്റാബേസ് സാങ്കേതികവിദ്യകൾ എന്നിവ ഉപയോഗിച്ച് വേഗത, വിശ്വാസ്യത, സുരക്ഷ എന്നിവ ഉറപ്പാക്കുന്നു.",
        "benefits": "ప్రయోజనాలు",
        "b1": "ఎక్కడి నుండైనా ఓటు వేయవచ్చు",
        "b2": "తక్షణ ఫలిత లెక్కింపు",
        "b3": "పర్యావరణ హిత కాగితం రహిత వ్యవస్థ",
        "b4": "సమయం మరియు ఖర్చు ఆదా చేస్తుంది",
        "back": "హోమ్‌కు తిరిగి వెళ్లండి",
        "footer_main": "ఆన్‌లైన్ ఓటింగ్ సిస్టమ్",
        "footer_gov": "భారత ప్రభుత్వం",
        "success": "നിങ്ങളുടെ വോട്ട് വിജയകരമായി സമർപ്പിച്ചു!",
        "thanks": "നിങ്ങളുടെ വോട്ട് രേഖപ്പെടുത്തിയതിന് നന്ദി.",
        "back": "ഹോം പേജിലേക്ക് മടങ്ങുക",
        "reg_title": "വോട്ടർ രജിസ്ട്രേഷൻ",
        "reg_desc": "പൗരന്മാർ വോട്ടർ ഐഡി, ആധാർ വിവരങ്ങൾ ഉപയോഗിച്ച് ഓൺലൈനായി രജിസ്റ്റർ ചെയ്യാം.",
        "login_title": "സുരക്ഷിത ലോഗിൻ",
        "login_desc": "ബഹുസ്തര സ്ഥിരീകരണ സംവിധാനം സുരക്ഷിതമായ വോട്ടർ പ്രവേശനം ഉറപ്പാക്കുന്നു.",
        "vote_title": "വോട്ട് ചെയ്യുക",
        "vote_desc": "വോട്ടർമാർ എവിടെയിരുന്നും ഡിജിറ്റൽ ആയി വോട്ട് ചെയ്യാം.",
        "dup_title": "ഇരട്ട വോട്ടിംഗ് തടയൽ",
        "dup_desc": "ഒരേ വോട്ടർ പല തവണ വോട്ട് ചെയ്യുന്നത് സംവിധാനം തടയുന്നു.",
        "lang_title": "ബഹുഭാഷാ പിന്തുണ",
        "lang_desc": "പ്രാദേശിക ഭാഷകളിൽ ലഭ്യമാക്കി സൗകര്യം ഉറപ്പാക്കുന്നു.",
        "cand_title": "സ്ഥാനാർത്ഥി വിവരങ്ങൾ",
        "cand_desc": "വോട്ട് ചെയ്യുന്നതിന് മുമ്പ് സ്ഥാനാർത്ഥിയും പാർട്ടിയും സംബന്ധിച്ച വിവരങ്ങൾ കാണിക്കുന്നു.",
        "live_title": "തത്സമയ ഫലങ്ങൾ",
        "live_desc": "തത്സമയം വോട്ടുകൾ എണ്ണുകയും ഫലങ്ങൾ സുതാര്യമായി കാണിക്കുകയും ചെയ്യുന്നു.",
        "admin_title": "അഡ്മിൻ മേൽനോട്ടം",
        "admin_desc": "തിരഞ്ഞെടുപ്പ് ഉദ്യോഗസ്ഥർ വോട്ടിംഗ് നിരീക്ഷിക്കുകയും സംവിധാനം നിയന്ത്രിക്കുകയും ചെയ്യുന്നു.",
        "footer": "ഓൺലൈൻ വോട്ടിംഗ് സിസ്റ്റം | ഇന്ത്യൻ സർക്കാർ",
        "service_title": "ഞങ്ങളുടെ സേവനങ്ങൾ",
        "eci": "ഇന്ത്യൻ തിരഞ്ഞെടുപ്പ് കമ്മീഷൻ",
        "manifesto_title": "പാർട്ടി മാനിഫെസ്റ്റോ (കച്ചികൊൽക്കൈ)",
        "manifesto_sub": "തിരഞ്ഞെടുപ്പ് നയങ്ങളും പങ്കാളികളുടെ വിവരങ്ങളും",
        "participants": "തിരഞ്ഞെടുപ്പ് പങ്കാളികൾ: 120 സ്ഥാനാർത്ഥികൾ",

        "p1": "സൗജന്യ വിദ്യാഭ്യാസ പദ്ധതി",
        "p2": "സ്ത്രീ ശാക്തീകരണം",
        "p3": "തൊഴിൽ സൃഷ്ടി പദ്ധതികൾ",
        "p4": "എല്ലാവർക്കും ആരോഗ്യ സേവനം",
        "p5": "പരിസ്ഥിതി സ്ഥിരതാ പ്രവർത്തനങ്ങൾ",
        "p6": "എല്ലാവർക്കും വിലകുറഞ്ഞ വീടുകൾ",
        "p7": "ഗ്രാമപ്രദേശങ്ങളിൽ ഡിജിറ്റൽ സാക്ഷരതയും ഇന്റർനെറ്റ് ആക്സസും",
        "p8": "കല, സംസ്കാരം & പൈതൃക സംരക്ഷണത്തിന് പിന്തുണ",
        "p9": "പുനരുപയോഗ ഊർജ്ജ പ്രോത്സാഹനം",
        "p10": "കുട്ടികളുടെ പോഷണവും മധ്യാഹ്നഭക്ഷണ മെച്ചപ്പെടുത്തലും",
        "p11": "പൊതു ഗതാഗത വികസനവും നവീകരണവും",
        "p12": "അഴിമതി വിരുദ്ധ സുതാര്യ നടപടികൾ",
        "p13": "മുതിർന്ന പൗരന്മാർക്ക് വിലകുറഞ്ഞ ആരോഗ്യ സേവനം",
        "p14": "നൈപുണ്യ വികസനവും തൊഴിൽപരിശീലനവും",
        "p15": "സ്ത്രീ സുരക്ഷയും നിയമ സഹായ പരിപാടികളും",
        "p16": "സ്റ്റാർട്ടപ്പുകളും ചെറുകിട ബിസിനസുകൾക്കും പിന്തുണ",
        "p17": "നഗര ഹരിത പ്രദേശങ്ങളും പാർക്ക് വികസനവും",
        "p18": "ഡിജിറ്റൽ ഭരണവും ഇ-സേവനങ്ങളുടെ വിപുലീകരണവും",
        "p19": "കർഷകർക്ക് ധനസഹായം",
        "p20": "സൗജന്യ മെഡിക്കൽ ക്യാമ്പുകൾ",
        "p21": "ഗ്രാമീണ വികസനം",
        "p22": "സ്ത്രീകളും കുട്ടികളും ക്ഷേമ പദ്ധതികൾ",
        "p23": "നഗര അടിസ്ഥാന സൗകര്യ വികസനം",
        "p24": "കുറഞ്ഞ വരുമാന കുടുംബങ്ങൾക്ക് കുറഞ്ഞ ചെലവിലുള്ള വീട്",
        "p25": "ശുദ്ധമായ കുടിവെള്ള പദ്ധതികൾ",
        "p26": "പുതുക്കാവുന്ന ഊർജ്ജ പ്രോത്സാഹനം",
        "p27": "ഡിജിറ്റൽ സാക്ഷരത & ഇ-ഗവേണൻസ് ആക്സസ്",
        "p28": "പൊതുജനാരോഗ്യം & വാക്സിനേഷൻ ക്യാമ്പുകൾ",
        "p29": "നൈപുണ്യ വികസനം & തൊഴിൽ പദ്ധതികൾ",
        "p30": "ഗതാഗതവും റോഡ് നവീകരണവും",
        "p31": "ചെറുകിട & ഇടത്തരം വ്യവസായങ്ങൾക്ക് പിന്തുണ",
        "p32": "പരിസ്ഥിതി സംരക്ഷണ പദ്ധതികൾ",
        "p33": "മുതിർന്ന പൗരന്മാർക്കുള്ള ക്ഷേമ പദ്ധതികൾ",
        "p34": "കുട്ടികളുടെ പോഷണം & ഉച്ചഭക്ഷണ മെച്ചപ്പെടുത്തൽ",
        "participants2": "തിരഞ്ഞെടുപ്പ് പങ്കാളികൾ: 110 സ്ഥാനാർത്ഥികൾ",
        "p35": "ഡിജിറ്റൽ ഇന്ത്യ വിപുലീകരണം",
        "p36": "സ്റ്റാർട്ടപ്പ് ഫണ്ടിംഗ്",
        "p37": "അടിസ്ഥാന സൗകര്യ വികസനം",
        "p38": "സ്മാർട്ട് സിറ്റി പദ്ധതികൾ",
        "p39": "നൈപുണ്യ വികസനവും തൊഴിൽപരിശീലനവും",
        "p40": "മേക്ക് ഇൻ ഇന്ത്യ പദ്ധതികൾ",
        "p41": "പുനരുപയോഗ ഊർജ്ജ പ്രോത്സാഹനം (സോളാർ & കാറ്റാടി)",
        "p42": "പൊതു ഗതാഗത നവീകരണം",
        "p43": "ആരോഗ്യ സേവനങ്ങളും ഇൻഷുറൻസ് പദ്ധതികളും",
        "p44": "വിദ്യാഭ്യാസ വായ്പ സഹായം",
        "p45": "ഗ്രാമീണ വികസനവും ജലസേചന പദ്ധതികളും",
        "p46": "ചെറുകിട & ഇടത്തരം സംരംഭങ്ങൾക്കുള്ള പിന്തുണ (SMEs)",
        "p47": "സ്ത്രീ ശാക്തീകരണ പരിപാടികൾ",
        "p48": "നഗര ഹരിത പ്രദേശങ്ങളും പാർക്ക് വികസനവും",
        "p49": "അഴിമതി വിരുദ്ധവും ഭരണ സുതാര്യതയും",
        "p50": "ഡിജിറ്റൽ ഭരണവും ഇ-സേവന വിപുലീകരണവും",
        "participants3": "തിരഞ്ഞെടുപ്പ് പങ്കാളികൾ: 95 സ്ഥാനാർത്ഥികൾ",
        "p51": "യുവ തൊഴിലവസര പദ്ധതി",
        "p52": "ആരോഗ്യ ഇൻഷുറൻസ്",
        "p53": "വിദ്യാഭ്യാസ വായ്പ മാപ്പ്",
        "p54": "വിലകുറഞ്ഞ വീടുകളുടെ പദ്ധതികൾ",
        "p55": "പുനരുപയോഗ ഊർജ്ജ പ്രോത്സാഹനം",
        "p56": "സ്ത്രീ ശാക്തീകരണവും സുരക്ഷാ പദ്ധതികളും",
        "p57": "കുട്ടികളുടെ പോഷണവും മധ്യാഹ്നഭക്ഷണ മെച്ചപ്പെടുത്തലും",
        "p58": "നൈപുണ്യ വികസനവും തൊഴിൽപരിശീലനവും",
        "p59": "ഗ്രാമീണ വികസനവും ജലസേചന പദ്ധതികളും",
        "p60": "ചെറുകിട ബിസിനസുകളും സ്റ്റാർട്ടപ്പുകൾക്കും പിന്തുണ",
        "p61": "പൊതു ആരോഗ്യ സേവനങ്ങളുടെ വിപുലീകരണം",
        "p62": "ഡിജിറ്റൽ ഭരണവും ഇ-സേവന ആക്സസും",
        "p63": "പരിസ്ഥിതി സംരക്ഷണ പ്രവർത്തനങ്ങൾ",
        "p64": "ഗതാഗതവും റോഡ് നവീകരണവും",
        "p65": "കല, സംസ്കാരം & പൈതൃക പ്രോത്സാഹനം",
        "p66": "മുതിർന്ന പൗരന്മാർക്കുള്ള ക്ഷേമ പദ്ധതികൾ",
        "participants4": "തിരഞ്ഞെടുപ്പ് പങ്കാളികൾ: 100 സ്ഥാനാർത്ഥികൾ",
        "p67": "പ്രാദേശിക തൊഴിലവസര പദ്ധതികൾ",
        "p68": "വിദ്യാഭ്യാസവും നൈപുണ്യ പരിശീലന പദ്ധതികളും",
        "p69": "ആരോഗ്യ സേവനങ്ങളുടെ വിപുലീകരണവും ആക്സസും",
        "p70": "ഗ്രാമീണ അടിസ്ഥാന സൗകര്യ വികസനം",
        "p71": "സമൂഹങ്ങൾക്ക് വിലകുറഞ്ഞ വീടുകൾ",
        "p72": "ചെറുകിട & ഇടത്തരം സംരംഭങ്ങൾക്കുള്ള പിന്തുണ (SMEs)",
        "p73": "സ്ത്രീകളും കുട്ടികളും ക്ഷേമ പദ്ധതികൾ",
        "p74": "പരിസ്ഥിതി സംരക്ഷണ പദ്ധതികൾ",
        "p75": "ഡിജിറ്റൽ സാക്ഷരത & ഇ-ഗവണൻസ് ആക്സസ്",
        "p76": "പൊതു ഗതാഗതവും റോഡ് നവീകരണവും",
        "p77": "പുനരുപയോഗ ഊർജ്ജ പദ്ധതികൾ",
        "p78": "യുവ ശാക്തീകരണവും തൊഴിൽപരിശീലനവും",
        "p79": "സമൂഹ വികസനവും ക്ഷേമ പദ്ധതികളും",
        "p80": "മുതിർന്ന പൗരന്മാർക്കുള്ള ക്ഷേമ പദ്ധതികൾ",
        "p81": "കല, സംസ്കാരം & പൈതൃക പ്രോത്സാഹനം",
        "participants5": "തിരഞ്ഞെടുപ്പ് പങ്കാളികൾ: 50 സ്ഥാനാർത്ഥികൾ",
        "p82": "പ്രാദേശിക വികസന പരിപാടികൾ",
        "p83": "മത്സ്യത്തൊഴിലാളി ക്ഷേമ പദ്ധതികൾ",
        "p84": "ചെറുകിട ബിസിനസുകൾക്ക് പിന്തുണ",
        "p85": "സമൂഹ ആരോഗ്യ പദ്ധതികൾ",
        "p86": "പ്രാദേശിക വിദ്യാഭ്യാസവും പരിശീലനവും",
        "p87": "വിലകുറഞ്ഞ വീടുകളുടെ പദ്ധതികൾ",
        "p88": "സ്ത്രീകളും കുട്ടികളും ക്ഷേമ പരിപാടികൾ",
        "p89": "പുനരുപയോഗ ഊർജ്ജവും പരിസ്ഥിതി പദ്ധതികളും",
        "p90": "ഗ്രാമീണ അടിസ്ഥാന സൗകര്യ വികസനം",
        "p91": "നൈപുണ്യ വികസനവും തൊഴിൽപരിശീലനവും",
        "p92": "പൊതു ഗതാഗതവും റോഡ് മെച്ചപ്പെടുത്തലും",
        "participants6": "തിരഞ്ഞെടുപ്പ് പങ്കാളികൾ: 30 സ്ഥാനാർത്ഥികൾ",
        "p93": "കൃഷി പിന്തുണ പരിപാടികൾ",
        "p94": "ഗ്രാമീണ അടിസ്ഥാന സൗകര്യ വികസനം",
        "p95": "യുവ ശാക്തീകരണവും വിദ്യാഭ്യാസവും",
        "p96": "നൈപുണ്യ വികസനവും തൊഴിൽപരിശീലനവും",
        "p97": "ഗ്രാമപ്രദേശങ്ങൾക്ക് ആരോഗ്യ സേവനങ്ങൾ",
        "p98": "സ്ത്രീകളും കുട്ടികളും ക്ഷേമ പരിപാടികൾ",
        "p99": "വിലകുറഞ്ഞ വീടുകളുടെ പദ്ധതികൾ",
        "p100": "ചെറുകിട ബിസിനസുകളും സംരംഭകത്വ പിന്തുണയും",
        "p101": "പുനരുപയോഗ ഊർജ്ജവും പരിസ്ഥിതി പദ്ധതികളും",
        "p102": "പൊതു ഗതാഗതവും റോഡ് നവീകരണവും",
        "participants7": "തിരഞ്ഞെടുപ്പ് പങ്കാളികൾ: 25 സ്ഥാനാർത്ഥികൾ"

    }
}


# ---------------- STORE USERS ----------------

users = []


# ---------------- PARTY VOTES ----------------

votes = {
    "TVK": 0,
    "DMK": 0,
    "Congress": 0,
    "ADMK": 0,
    "NTk": 0,
    "BJP": 0,
    "PMK": 0
}

# ---------------- SET LANGUAGE ----------------

@app.route("/set_language/<lang>")
def set_language(lang):
    session["lang"] = lang
    return redirect(request.referrer or url_for("home"))


# ---------------- HOME ----------------

@app.route("/")
@app.route("/home")
def home():
    lang = session.get("lang", "en")
    texts = languages.get(lang, languages["en"])
    return render_template("home.html", texts=texts, lang=lang)


# ---------------- ABOUT ----------------

@app.route("/about")
def about():
    lang = session.get("lang", "en")
    texts = languages.get(lang, languages["en"])
    return render_template("about.html", texts=texts, lang=lang)


# ---------------- SERVICE ----------------

@app.route("/service")
def service():
    lang = session.get("lang", "en")
    texts = languages.get(lang, languages["en"])
    return render_template("service.html", texts=texts, lang=lang)


# ---------------- MANIFESTO ----------------

@app.route("/manifesto")
def manifesto():
    lang = session.get("lang", "en")
    texts = languages.get(lang, languages["en"])
    return render_template("manifesto.html", texts=texts, lang=lang)
#-------------------CONSTITUENCY---------------

@app.route('/constituency')
def constituency():
    return render_template("constituency.html", constituencies=constituencies)


# ---------------- ADMIN LOGIN ----------------

@app.route("/admin", methods=["GET", "POST"])
def admin():

    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]

        if username == "admin" and password == "admin123":
            session["admin"] = True
            return redirect("/secure_result")
        else:
            return "Invalid Admin Login ❌"

    return render_template("admin.html")


# ---------------- SECURE RESULT ----------------

@app.route("/secure_result")
def secure_result():

    if "admin" not in session:
        return redirect("/admin")

    return render_template("result.html", votes=votes)

# ---------------- REGISTER ----------------

@app.route("/register", methods=["GET", "POST"])
def register():

    if request.method == "POST":

        voterid = request.form["voterid"]

        for user in users:
            if user["voterid"] == voterid:
                return "Voter ID already registered ❌"

        users.append({
            "name": request.form["name"],
            "email": request.form["email"],
            "address": request.form["address"],
            "phone": request.form["phone"],
            "aadhar": request.form["aadhar"],
            "voterid": voterid,
            "username": request.form["username"],
            "password": request.form["password"],
            "voted": False
        })

        return redirect("/login")

    return render_template("register.html")


# ---------------- LOGIN ----------------

@app.route("/login", methods=["GET", "POST"])
def login():

    if request.method == "POST":

        username = request.form["username"]
        password = request.form["password"]

        for user in users:
            if user["username"] == username and user["password"] == password:

                if user["voted"]:
                    return "You already voted ❌"

                session["user"] = username
                return redirect("/vote")

        return "Invalid Login ❌"

    return render_template("login.html")


# ---------------- VOTE ----------------

@app.route("/vote", methods=["GET", "POST"])
def vote():

    global votes

    if "user" not in session:
        return redirect("/login")

    if request.method == "POST":

        party = request.form["party"]

        if party in votes:
            votes[party] += 1

        for user in users:
            if user["username"] == session["user"]:
                user["voted"] = True

        return redirect("/success")   # ✅ Now correct

    return render_template("vote.html", parties=votes.keys())

# ---------------- SUCCESS PAGE ----------------

@app.route("/success")
def success():
    return render_template("success.html")



# ---------------- LOGOUT ----------------

@app.route("/logout")
def logout():
    session.pop("user", None)
    session.pop("admin", None)
    return redirect("/home")


# ---------------- RUN ----------------

if __name__ == "__main__":
    app.run(debug=True)

    #---------------new----------------
import os

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=True)